### ISSUE TITLE
Debugging - MC-1.12.2 Forge 512 - Issues with entity reloading and cache

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [PrinceOfAmber/EmberRootZoo#17]
https://gist.github.com/P3rf3ctXZer0/e358ff02428bd8923f86d4c4cae6b64f

**Comment by Lothrazar** [comment]
I could be wrong, but I don't see anything related to this mod on the list.  Looks like only journeymap? Am i missing something?


at journeymap.client.data.DataCache.getPlayer(DataCache.java:303)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190)
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33)

and 

[21:08:34] [Server thread/ERROR] [journeymap]: Error handling WorldEvent.Unload
java.lang.NullPointerException: null
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) [WorldEventHandler.class:1.12.2-5.5.0rc1]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_599_WorldEventHandler_onUnload_Unload.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:355) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:786) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Comment by P3rf3ctXZer0** [comment]
Error Sorry I gave you the wrong report ... I must have been tired.
